### ISSUE TITLE
rulp gem version is not latest

### ISSUE THREAD

**Issue by rvyas** [wouterken/rulp#14]
gemserver is showing 0.44 from 2017.  the latest changes from master (2021) are not released. Is there a disconnect?

![image](https://github.com/wouterken/rulp/assets/2732444/804cab8c-150e-4319-b68c-cabe6455d7d8)

Would it be possible to push latest version to gemserver?

I found as I couldn't use 0.44 with Rails and noticed there is a fix (#5) to use ENV already in place for custom suffix.

**Comment by wouterken** [comment]
Hi @rvyas 
I've just pushed those changes inside version 0.45 now.

Shout out if any issues. 🙏
