### ISSUE TITLE
Question regarding NoMethodError and given[]

### ISSUE THREAD

**Issue by jonahgeorge** [wouterken/rulp#3]
Hey there,
I've been encountering this error while constructing some unit tests and I'm curious if you've seen this before (very likely is a logic error on my part but wanted to double-check).

**Explanation**
It appears to only happen when the length of `@sections` is 1, any value higher and this error disappears. The length of `@students` can be anything and it still works.

```
NoMethodError:
  undefined method `variables' for VAR56-26(b)[undefined]:BV
# /Users/jonahgeorge/.gem/ruby/2.3.0/gems/rulp-0.0.26/lib/extensions/kernel_extensions.rb:35:in `method_missing'
# /Users/jonahgeorge/.gem/ruby/2.3.0/gems/rulp-0.0.26/lib/rulp/rulp.rb:103:in `each'
# /Users/jonahgeorge/.gem/ruby/2.3.0/gems/rulp-0.0.26/lib/rulp/rulp.rb:103:in `flat_map'
# /Users/jonahgeorge/.gem/ruby/2.3.0/gems/rulp-0.0.26/lib/rulp/rulp.rb:103:in `[]'
# ./lib/integer_linear_program.rb:79:in `block in fte_contraint'
# /Users/jonahgeorge/.gem/ruby/2.3.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
# /Users/jonahgeorge/.gem/ruby/2.3.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
# ./lib/integer_linear_program.rb:76:in `fte_contraint'
# ./lib/integer_linear_program.rb:16:in `initialize'
# ./spec/lib/integer_linear_program_spec.rb:74:in `new'
# ./spec/lib/integer_linear_program_spec.rb:74:in `block (2 levels) in <top (required)>'
```

``` ruby
def fte_contraint
  @students.each do |student|
    variables = @sections.map { |section| VAR_b(student.id, section.id) }
    constraint = (variables.sum <= (student.fte / @fte_per_section))
    @problem[ constraint ]
  end
end
```

**What I Think Is Happening**
When the length of `@sections` is 1, the resulting length of `variables` is also 1. Because of this, the constraint turns into the form:

``` ruby
@problem[ VAR_b(int, int) <= int ]
```

Its my understanding that this library expects constraints with only one variable to be defined via the `given[]` method. I was able to get around this with the following code, but I'm curious if there's a way to achieve this using a standard constraint instead of `given[]`. 

``` ruby
def fte_contraint
  @students.each do |student|
    variables = @sections.map { |section| VAR_b(student.id, section.id) }
    constraint = (variables.sum <= (student.fte / @fte_per_section))
    if variables.length > 1
      @problem[ constraint ]
    else
      given[ constraint ]
    end
  end
end
```

**Comment by jonahgeorge** [comment]
Fixed by 89f4502d8, thank you!

**Comment by wouterken** [comment]
Wow you're quick! I was going to leave you a comment after I got home from work today, but looks like you've already discovered my commit.

Just in case you're interested... 
While a constraint with a single variable of the form 
`X < 10`
isn't noticeably different from a multi-variable constraint
`X + Y < 20`
In the context of Rulp and many common solvers the two can be treated differently.
The first example can be expressed as bounds on a variable
Where the second example is really a constraint

Rulp also makes the distinction between variable bounds and constraints and doesn't require variable bounds to be passed into the model. (These bounds instead live on the variable itself). However as you've pointed out this leads to an inconsistent API in some cases.

So as a fix we will now happily accept variable bounds inside the square brackets (and these bounds still hold) but they are simply ignored by the code that generates multi-variable constraints

**Comment by jonahgeorge** [comment]
Thanks so much for explaining this (and making the modification). It definitely now makes sense that the constraints live on the variable.
