### ISSUE TITLE
Rails & Rulp Integration error

### ISSUE THREAD

**Issue by joseglego** [wouterken/rulp#5]
I'm working with rails and I'm trying to build a `RESTful API` which solved LP problems using `rulp`

When I try to define my `Api` module I can't because `rulp` defined it as a variable of a LP problem. Based on it finished on `i`. Something like this:
```
module Api
  module v1
    class LinearProgramingSolversController
      ...
    end
  end
end
```
 
I think, we can rewrite the suffixes as `lpi`, `lpf` and `lpb` or just use `_i`, `_b` y `_f`. So, it'll be less problematic to work in a general context with other gems and applications. 

Or even better, the user can define which suffixes use

What do you think?

**Comment by wouterken** [comment]
Hi @joseglego 
You're right that it doesn't play nicely with Rails due to both of these relying on using `const_missing`.

Making this configurable would be nice.

This is something I am hoping to implement in the future, but feel free to submit a PR if you would like to suggest an approach yourself.

In the meantime, to get your API working, one thing you might want to try is to write:
```ruby
gem 'rulp', require: false
```
In your gemfile. Using `require: false` and then explicitly using `require 'rulp'` where you need it will allow the Rails autoloading to get in first, before Rulp

**Comment by joseglego** [comment]
Hi @wouterken 

It was a good hint, it works when I'm working on local server. But, it doesn't work in Heroku.

**Comment by joseglego** [comment]
Our fast solution was adapt your gem to our needs, and define the suffixes as: `lpi`, `lpf` and `lpb` instead of `i`, `b` and `f`, you can check it:
https://github.com/platanus/rulp/tree/feat/fromIBFtoLPIBF

I'm pretty sure it won't be good for you because it'll generate incompatibility with other users of your gem and the previous version.

BUT, I'll think in the idea of configurable suffixes and how to define before Heroku runs. We prefer come back to the original gem and get the benefits of your next updates.

**Comment by wouterken** [comment]
Thanks @joseglego 

I'm glad you've been able to work around this.

re: The error on Heroku, this is an interesting observation. 

In theory as long as the affected constant has been defined/loaded before you require `rulp` you should not encounter this error. 

If this is not the case on Heroku it would seem likely that either 
* `config.eager_load == false` inside the environment configuration file; **or** 
* the problem file does not reside within a location present inside `Rails.application.config.eager_load_paths`. With a bit of tweaking I'm sure it's possible to get it to work, but since you've already found a way around it you shouldn't need to invest any extra effort to investigate this.

Either way, your suggestion of making this a configurable parameter is sound and something I will certainly look at in the future.

**Comment by jonahgeorge** [comment]
@joseglego Here's an example of how I got Rulp and Rails working together on Heroku:

- https://github.com/jonahgeorge/gta-assignment/blob/master/app/controllers/administrator/assignments_controller.rb#L47-L52
- https://github.com/jonahgeorge/gta-assignment/blob/master/lib/integer_linear_program.rb
- https://github.com/jonahgeorge/gta-assignment/blob/master/Gemfile#L8
- https://github.com/jonahgeorge/gta-assignment/blob/master/Aptfile
  - https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt

**Comment by joseglego** [comment]
Yes @jonahgeorge, as you say it can work. In fact, it works for me.

My problem came when I try to define a RESTful Api, which use to be named `Api`, Why? Because it start with `A` and ends with `i`, So, It can be an Integer variable for Rulp. I tried:

- add `require: false` in `Gemfile`
- add `require 'rulp'` in my specific file. 
- add an `Aptfile` with `glpk-utils` 
- add the `heroku-buildpack-apt` in index 1. 

But my heroku app doesnt work. Maybe I can create an small project to share and check which is the problem, I may be missing something (for this reasson I listed before my steps)

**Comment by jonahgeorge** [comment]
Yea, if you can reproduce it in a small project I'd be happy to take a look over the weekend

**Comment by joseglego** [comment]
I've been working in the example.

So, we have the repo:
https://github.com/joseglego/rulp-example

You can find 2 branches:
- `master`: It works cool, It is has a controller which process the data, and everything works ok.
- `api`: It's like the previous one, but also include an endpoint (`solution`) which can give you the same information in a `json` format. In the index, we have a new button which works with this endpoint. It works in local server until the first error. After the first error I got a message like:

```
Unable to load application: TypeError: Ap(i)[undefined] is not a class/module
TypeError: Ap(i)[undefined] is not a class/module
```

As answer to ALL requests. Even, for the index view.

I have 2 servers to show you this, each server has a branch:
https://pl-rulp-example-production.herokuapp.com [`master` branch] - works ok
https://pl-rulp-example-staging.herokuapp.com [`api` branch] - crashed after deploy

Staging Log: https://gist.github.com/joseglego/64711e5132ad919bcbaeb4563b35c428

Feel free to download the code & check, or ask for more information. I'll be glad to help

**Comment by joseglego** [comment]
@wouterken, @jonahgeorge 

I've been working in this. I tried with the small project which I mentioned before, and the api crashed the application. So, based on the custom suffix idea, I created one new branch:

`api-v2` which include a custom rulp which has custom suffixes included 😄 . I worked on this during the weekend. So, you can check it out here: https://github.com/platanus/rulp/tree/feat/customSuffix

in Resume, we have 3 servers, 3 branches, and a custom rulp (ready to include in yours):
1. Server with rails way - `master` branch: https://pl-rulp-example-production.herokuapp.com [status: ok]
2. Server with Api way - `api` branch: https://pl-rulp-example-staging.herokuapp.com [status: crashed]
3. Server with Api way - `api-v2` branch, rulp with `feat/customSuffix` branch: https://pl-rulp-example-dev.herokuapp.com [status: ok]

Let me know if you are interested and I'll do the PR. 

the `feat/customSuffix` use local environments, it search `rulp_CLASS` or use the default value for each variable, and has a class method to know which is the suffix to use.

**Comment by wouterken** [comment]
Thanks @joseglego, your fix looks good. 

One small thing I would suggest is to use `ALL_UPPER_CASE` for the environment variable names as is customary.

Perhaps we can also make the name a little more descriptive. I.e. RULP_BV is a little ambiguous, something like RULP_BV_SUFFIX tells us a little more about what the environment variable is actually used for. With these two small things addressed I would be happy to accept a PR 👍

**Comment by wouterken** [comment]
https://github.com/wouterken/rulp/pull/6/commits/2e9c0b6cb07e4ef384d10405a483eded36ad0738
