### ISSUE TITLE
"No such file or directory",

### ISSUE THREAD

**Issue by tiagofumo** [wouterken/rulp#7]
So I am trying to find a set of combinations of foods that are cheap and meet some nutrition requirements for different types of diets (like keto for example).

I have a set of food nutritional info:
```ruby
foods = {
  Lettuce: {
    serving: 100,
    carbs: 2.9,
    protein: 1.4,
    fat: 0.2,
    fiber: 1.3,
    sugar: 0.8,
    sodium: 28,
    potassium: 194,
    package: 360,
    cost: 1.0,
  },
  Tomato: {
    serving: 100,
    carbs: 3.9,
    protein: 0.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
    potassium: 237,
    package: 1000,
    cost: 3.0,
  },
  ...
}
```
I add some extra fields:
```ruby
foods.each do |key, food|
  ['carbs', 'protein', 'fat', 'potassium', 'sodium'].each do |sym|
    food["#{sym}_per_unit".to_sym] = (food[sym.to_sym]/food[:serving]).round(3)
  end

  food[:carbs_cal] = (food[:carbs] * 4).round(3)
  food[:protein_cal] = (food[:protein] * 4).round(3)
  food[:fat_cal] = (food[:fat] * 9).round(3)

  food[:carbs_cal_per_unit] = (food[:carbs_cal]/food[:serving]).round(3)
  food[:protein_cal_per_unit] = (food[:protein]/food[:serving]).round(3)
  food[:fat_cal_per_unit] = (food[:fat]/food[:serving]).round(3)

  food[:net_carbs] = (food[:carbs] - food[:fiber]).round(2)
  food[:cost_per_unit] = (food[:cost]/food[:package]).round(3)

end
```

And I have these expressions:
```ruby

expressions = foods.keys.map(&C_i)
objective = expressions.map {|i| get_food(i)[:cost_per_unit] * i}.inject(:+)

carbs_cal = expressions.map {|i| get_food(i)[:carbs_cal_per_unit] * i}.inject(:+)
protein_cal = expressions.map {|i| get_food(i)[:protein_cal_per_unit] * i}.inject(:+)
fat_cal = expressions.map {|i| get_food(i)[:fat_cal_per_unit] * i}.inject(:+)
total_cal = carbs_cal + protein_cal + fat_cal

total_sodium = expressions.map {|i| get_food(i)[:sodium_per_unit] * i}.inject(:+)
total_potassium = expressions.map {|i| get_food(i)[:potassium_per_unit] * i}.inject(:+)

Rulp::Min(objective) [
  carbs_cal <= 80,
  protein_cal <= 200,
  fat_cal >= 1120,
 
  # carbs_cal * 0.95 - protein_cal * 0.05 - fat_cal * 0.05 <= 0,

  # carbs_cal + protein_cal + fat_cal >= 1500,

  total_potassium >= 2000,
].glpk

objective.evaluate
```

So this works, but If I use something like this:
```ruby
Rulp::Min(objective) [
  carbs_cal + protein_cal + fat_cal >= 1500,
  total_potassium >= 2000,
].glpk
```
I get an error: "No such file or directory @ rb_sysopen - /tmp/rulp-899.sol". From the log info I have the lines:
```
D, [2019-03-06T13:39:08.937336 #31024] DEBUG -- :  --lp /tmp/rulp-499.sol --cuts --output /tmp/rulp-899.sol

D, [2019-03-06T13:39:08.937351 #31024] DEBUG -- : Reading problem data from '/tmp/rulp-499.sol'...

D, [2019-03-06T13:39:08.937368 #31024] DEBUG -- : /tmp/rulp-499.sol:5: multiple use of variable 'CLettuce' not allowed
```
Looking at the [source code](https://github.com/wouterken/rulp/blob/fa870449a24029ec58194a50a3357b6f5143bc51/lib/solvers/solver.rb#L5), I can see that 2 different /tmp/rulp-xxx.sol files are created, but like I said, if I use different expressions I get no errors. I tried adding these to lib/solvers/glpk.rb at the beginning of the store_results method:
```ruby
`touch #{@filename}`
`touch #{@outfile}`
```
but I get another error "lib/extensions/kernel_extensions.rb:35:in 'method_missing': undefined method 'split' for nil:NilClass (NoMethodError)".

If I use these:
```ruby
Rulp::Min(objective) [
  carbs_cal * 0.95 - protein_cal * 0.05 - fat_cal * 0.05 <= 0,
  total_potassium >= 2000,
].glpk
```
I get another error "lib/extensions/kernel_extensions.rb:35:in 'method_missing': undefined method '*' for #<Expressions:0x00005652feec0070>"
This time, the Log doesn't show anything, so I think GLPK isn't even initialized, which means I am probably using wrong syntax.

**Comment by wouterken** [comment]
Hi @tiagofumo, 
The problem is that in each expression the solver only allows an LP variable to be referenced once.
The error in the GLPK log has a clue:

> /tmp/rulp-499.sol:5: multiple use of variable 'CLettuce' not allowed

The problem statement is 
`carbs_cal + protein_cal + fat_cal >= 1500`

- `carbs_cal` is equal to `0.116 CLettuce + 0.156 CTomato + ....`
- `protein_cal` is equal to `0.014 CLettuce + 0.009 CTomato + ....`
- `fat_cal` is equal to `0.002 CLettuce + 0.002 CTomato + ....`
and so on, so when you add these together, you get one large statement:

`0.116 CLettuce + 0.156 CTomato + .... + 0.014 CLettuce + 0.009 CTomato + ... + 0.002 CLettuce + 0.002 CTomato` 
Notice how the statement refers to CLettuce and CTomato multiple times, this unfortunately is not allowed.

We instead need to make sure that they are included in the statement only once.
Luckily the above is equivalent to, and can be refactored to `(0.116 + 0.014 + 0.002 ) CLettuce + (0.156 + 0.009 + 0.002 ) CTomato + ...`

If you give the statement to Rulp like this instead, it'll solve successfully.

There's a number of ways to refactor this to get the desired result, as a quick proof here's a little method that'll merge multiple expressions in the form you've given into a single expression that contains each variable only once
```ruby
def merge_expressions(*expression_list)
  expression_list.flat_map(&:expressions).group_by(&:lv).map{|lv, group| lv * group.map(&:operand).sum }.sum
end

Rulp::Min(objective) [
  merge_expressions(carbs_cal,protein_cal,fat_cal) >= 1500,
  total_potassium >= 2000,
].glpk

puts "Total calories: #{objective.evaluate}"
puts "This much lettuce: #{CLettuce_i.value}"
```

**Comment by tiagofumo** [comment]
Thanks for the reply. You explained it really well.

Yesterday (before your reply) me and my friend were trying to find a solution, and we figured that out:

> Notice how the statement refers to CLettuce and CTomato multiple times, this unfortunately is not allowed.
> 
> We instead need to make sure that they are included in the statement only once.
> Luckily the above is equivalent to, and can be refactored to (0.116 + 0.014 + 0.002 ) CLettuce + (0.156 + 0.009 + 0.002 ) CTomato + ...

And we solved it this way:
```ruby
total_cal = expressions.map {|i| get_food(i)[:total_cal_per_unit] * i}.inject(:+)
cal_goal = 1500
Rulp::Min(objective) [
  carbs_cal <= cal_goal * 0.05,
  protein_cal >= cal_goal * 0.18,
  protein_cal <= cal_goal * 0.2,
  fat_cal >= cal_goal * 0.75,
  total_cal >= cal_goal,
  total_potassium >= 2000,
]
```
But I didn't like the way it ended up, and I am going to add new constraints, so the `merge_expressions` method is going to be helpful. I am using the `merge_expressions` method, and based on it I also added one for subtracting and another one for multiplying expressions and I can do anything now.

I know how boring it can be to have to answer beginner's questions on issues, so I would like to thank you again for that, it helped a lot.
